// frontend/src/App.vue
<script setup>
import HomeVue from './components/Home.vue';
</script>

<template>
  <main class="bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-100 min-h-screen">
    <div class="container mx-auto py-8 2xl:px-28 xl:px-28 lg:px-28 md:px-10 px-8">
      <HomeVue></HomeVue>
    </div>
  </main>
</template>

// app/src/App.svelte
<script lang="ts">
  import Home from "./lib/Home.svelte";
  import type { Config } from "./types";

  const fetcher = async () => {
    const res = await fetch("/config");
    const data: Config = await res.json();
    return data;
  };
</script>

<main
  class="bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-100 min-h-screen"
>
  {#await fetcher()}
    <p class="flex items-center justify-center">Loading ...</p>
  {:then data}
    <Home config={data} />
  {/await}
</main>
